services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.deployment
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always
  database:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: billiards_manager_production
    restart: always
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
